name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build I Guess
    runs-on: ubuntu-latest
    
    steps:
    - name: I hate this format 
      # You may pin to the exact commit or the version.
      # uses: garygrossgarten/github-action-ssh@d2ce399984eed21f8cf2a26d28ba309e1ed52fc5
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        # Command to execute on the remote server.
        command: './update.sh'
        # Hostname or IP address of the server.
        host: ${{ secrets.HOST }}
        # Username for authentication.
        username: ${{ secrets.USERNAME }}
        # Port number of the server.
        port: ${{ secrets.PORT }}
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        privateKey: ${{ secrets.PRIVATEKEY }}
        # Password for password-based user authentication.
        #password: # optional
        # For an encrypted private key, this is the passphrase used to decrypt it.
        #passphrase: # optional
        # Try keyboard-interactive user authentication if primary user authentication method fails.
        #tryKeyboard: # optional
